### ISSUE TITLE
No collection for path: collectionName

### ISSUE THREAD

**Issue by VisetDev** [firecmsco/firecms#638]
When trying to list a "type:reference" property under a subcollection, ErrorView arise:

![image](https://github.com/firecmsco/firecms/assets/108474478/441ebd2c-c1d3-41a6-b50e-38cabf5e6e02)

Entities under subcollections stores references to documents under '/home/collections/visets' thus view configuration is as follow:

```
const reference = buildProperty({
		dataType: 'reference',
		path: "home/collections/visets",
		readOnly: true,
		name: 'In Collection',
		previewProperties: ["title"],
        columnWidth: 400,
	
});
```

onFetch(entity) log:

```
values: 
reference:  On2 
             id: "75b2b694dd42b88a8fc3"
             path: "home/collections/visets"
```

the same structure works fine if referenced collection is under root: '/visets' (for instance)

Collection '/home/collections/visets' is already created in firecms and works just fine.

My asumptions is somehow firecms reference path is not parsing paths in the form : "/collection/document/collection/" (deep further root)
